### PR TITLE
Patch team 6 judge (Array not initialised)

### LINKED ISSUE #359: [INFRA/IIGO] Panic when initialResources is increased
Repro steps:
```
go run  . --initialResources 100000
```

logs:
```
2021/01/08 19:47:50 [SERVER]: start runTurn
2021/01/08 19:47:50 [SERVER]: TURN: 1, Season: 1
2021/01/08 19:47:50 [SERVER]: start startOfTurn
2021/01/08 19:47:50 [Team6]: Configuration has been updated
2021/01/08 19:47:50 [Team6]: Friendship information has been updated
2021/01/08 19:47:50 [Team6]: There are 6 islands left in this game
2021/01/08 19:47:50 [Team1]: Emotional state: Normal
2021/01/08 19:47:50 [Team1]: Resources: 100000
2021/01/08 19:47:50 [Team3]: Our Status: {Resources:100000 LifeStatus:Alive CriticalConsecutiveTurnsCounter:0}
2021/01/08 19:47:50 [SERVER]: finish startOfTurn
2021/01/08 19:47:50 [SERVER]: start runOrgs
2021/01/08 19:47:50 [SERVER]: start runIIGO
2021/01/08 19:47:50 [SERVER]: President Team3, Speaker Team1, Judge Team2
2021/01/08 19:47:50 [SERVER]: [EXECUTIVE]: Tax: map[Team1:0 Team2:0 Team3:933.4766869216942 Team4:0 Team5:0 Team6:0]
2021/01/08 19:47:50 [SERVER]: [EXECUTIVE]: Resource Allocation: map[Team1:-0 Team2:-0 Team3:56.0000000000126 Team4:-6.298915645395252e-12 Team5:-6.298915645395252e-12 Team6:-0]
2021/01/08 19:47:50 [SERVER]: [LEGISLATURE]: Rule vote with islands [Team1 Team2 Team3 Team4 Team5 Team6] allowed to vote
2021/01/08 19:47:50 [SERVER]: [RULE VOTE]: Votes: [Approve Approve Approve Approve Approve Abstain]
2021/01/08 19:47:50 [SERVER]: [LEGISLATURE]: Rule: salary_paid_judge , voted in by islands: true , result heeded by speaker: true
2021/01/08 19:47:50 [SERVER]: Cannot pay IIGO salary
2021/01/08 19:47:50 [SERVER]: finish runIIGO
2021/01/08 19:47:50 [SERVER]: start runIIFO
2021/01/08 19:47:50 [SERVER]: start runPredictionSession
2021/01/08 19:47:50 [Team1]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:50 [Team3]: Final Prediction: [{NaN NaN NaN 9223372036854775808 NaN}]
2021/01/08 19:47:50 [Team4]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:50 [Team5]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:50 [Team6]: Final Prediction: [{60.64 60.64 35.64 1844674407370955264 34.7}]
2021/01/08 19:47:50 [SERVER]: finish runPredictionSession
2021/01/08 19:47:50 [SERVER]: Run Forage Predictions
2021/01/08 19:47:50 [SERVER]: Getting Forage Information
2021/01/08 19:47:50 [Team1]: Sharing forage info: {{DeerForageType 0} 0 [] Team1}
2021/01/08 19:47:50 [SERVER]: Distributing Forage Information
2021/01/08 19:47:50 [SERVER]: Finish Running Forage Predictions
2021/01/08 19:47:50 [SERVER]: finish runIIFO
2021/01/08 19:47:50 [SERVER]: start runIITO
2021/01/08 19:47:50 [SERVER]: start runGiftSession
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team3:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]}]
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team3:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]}]
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team3:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]}]
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team3:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team3:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:50 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:50 [Team6]: The island[Team3] accepts the amount[11.785113019775793] because they [0]
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team4 from Team3: 12.5
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team5 from Team3: 12.5
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team6 from Team3: 4.999999999999999
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team1 from Team3: 12.5
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team2 from Team3: 12.5
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team3 from Team6: 11.785113019775793
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team3 from Team1: 11.785113019775793
2021/01/08 19:47:50 [SERVER]: [IITO]: Gifts to Team6 from Team1: 10
2021/01/08 19:47:50 [SERVER]: finish runGiftSession
2021/01/08 19:47:50 [SERVER]: start runIntendedContributionSession
2021/01/08 19:47:50 [SERVER]: finish runIntendedContributionSession
2021/01/08 19:47:50 [SERVER]: finish runIITO
2021/01/08 19:47:50 [SERVER]: finish runOrgs
2021/01/08 19:47:50 [SERVER]: start endOfTurn
2021/01/08 19:47:50 [SERVER]: start runIIGOAllocations
2021/01/08 19:47:50 [SERVER]: Gave 0 to Team4 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: Gave 0 to Team5 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: Gave 0 to Team6 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: Gave -0 to Team1 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: Gave 0 to Team2 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: Gave 0 to Team3 (reason: allocation)
2021/01/08 19:47:50 [SERVER]: finish runIIGOAllocations
2021/01/08 19:47:50 [SERVER]: start runForage
2021/01/08 19:47:50 [Team1]: [Forage decision]: flip
2021/01/08 19:47:50 [SERVER]: Took 9.377796898048464 from Team4 (reason: deer hunt participation)
2021/01/08 19:47:50 [SERVER]: Took 16.272799219801936 from Team5 (reason: fishing participation)
2021/01/08 19:47:50 [SERVER]: Took 20000 from Team6 (reason: deer hunt participation)
2021/01/08 19:47:50 [SERVER]: Took 30000 from Team1 (reason: deer hunt participation)
2021/01/08 19:47:50 [SERVER]: Took 20 from Team2 (reason: fishing participation)
2021/01/08 19:47:50 [SERVER]: Took 0 from Team3 (reason: deer hunt participation)
2021/01/08 19:47:50 [SERVER]: Team3 did not contribute resources and will not participate in this foraging round.
2021/01/08 19:47:50 [SERVER]: start runDeerHunt
2021/01/08 19:47:50 [SERVER]: Gave 0.034040383205066055 to Team4 (reason: Deer hunt return)
2021/01/08 19:47:50 [SERVER]: Gave 72.5978256410094 to Team6 (reason: Deer hunt return)
2021/01/08 19:47:51 [Team6]: Forage History Updated: Type DeerForageType ,Conribution: 20000 ,Return: 72.5978256410094
2021/01/08 19:47:51 [SERVER]: Gave 108.89673846151409 to Team1 (reason: Deer hunt return)
2021/01/08 19:47:51 [Team1]: [Forage result]: DeerForageType(30000.000) | Expectation: +0.000 | Reward: +108.897 | Error: -100%
2021/01/08 19:47:51 [SERVER]: Deer hunt report: {"ForageType":"DeerForageType","InputResources":50009.37779689804,"NumberParticipants":3,"NumberCaught":4,"TotalUtility":181.52860448572852,"CatchSizes":[64.01619328509351,18.19793571378622,80.239234314334,19.075241172514765],"Turn":1}
2021/01/08 19:47:51 [SERVER]: Updating deer population after 4 deer hunted
2021/01/08 19:47:51 [SERVER]: [DEERPOPULATION]: P(t): 8.73.     Population after 4 deer hunted: 8,      population at end of turn (after regeneration): 8
2021/01/08 19:47:51 [SERVER]: finish runDeerHunt
2021/01/08 19:47:51 [SERVER]: start runFishHunt
2021/01/08 19:47:51 [SERVER]: Gave 29.42685976274612 to Team5 (reason: Fishing return)
2021/01/08 19:47:51 [SERVER]: Gave 29.42685976274612 to Team2 (reason: Fishing return)
2021/01/08 19:47:51 [SERVER]: Fishing expedition report: {"ForageType":"FishForageType","InputResources":36.27279921980194,"NumberParticipants":2,"NumberCaught":5,"TotalUtility":58.85371952549224,"CatchSizes":[9.219552904973892,10.491508043284016,12.250361935103452,11.716990010074612,15.175306632056264],"Turn":1}
2021/01/08 19:47:51 [SERVER]: finish runFishHunt
2021/01/08 19:47:51 [SERVER]: finish runForage
2021/01/08 19:47:51 [SERVER]: start runIIFOEndOfTurn
2021/01/08 19:47:51 [SERVER]: finish runIIFOEndOfTurn
2021/01/08 19:47:51 [SERVER]: start runIITOEndOfTurn
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team1 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team1 (reason: GIVE: [IITO]: Team1 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team2 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team2 (reason: GIVE: [IITO]: Team2 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team4 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team4 (reason: GIVE: [IITO]: Team4 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team5 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team5 (reason: GIVE: [IITO]: Team5 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 4.999999999999999 from Team3 (reason: TAKE: [IITO]: Team6 received gift from Team3: 4.999999999999999)
2021/01/08 19:47:51 [SERVER]: Gave 4.999999999999999 to Team6 (reason: GIVE: [IITO]: Team6 received gift from Team3: 4.999999999999999)
2021/01/08 19:47:51 [Team6]: The gift[4.999999999999999] has been received from the island[Team3]
2021/01/08 19:47:51 [SERVER]: Took 11.785113019775793 from Team6 (reason: TAKE: [IITO]: Team3 received gift from Team6: 11.785113019775793)
2021/01/08 19:47:51 [SERVER]: Gave 11.785113019775793 to Team3 (reason: GIVE: [IITO]: Team3 received gift from Team6: 11.785113019775793)
2021/01/08 19:47:51 [Team6]: The gift[11.785113019775793] has been sent to the island[Team3]
2021/01/08 19:47:51 [SERVER]: Took 10 from Team1 (reason: TAKE: [IITO]: Team6 received gift from Team1: 10)
2021/01/08 19:47:51 [SERVER]: Gave 10 to Team6 (reason: GIVE: [IITO]: Team6 received gift from Team1: 10)
2021/01/08 19:47:51 [Team6]: The gift[10] has been received from the island[Team1]
2021/01/08 19:47:51 [SERVER]: Took 11.785113019775793 from Team1 (reason: TAKE: [IITO]: Team3 received gift from Team1: 11.785113019775793)
2021/01/08 19:47:51 [SERVER]: Gave 11.785113019775793 to Team3 (reason: GIVE: [IITO]: Team3 received gift from Team1: 11.785113019775793)
2021/01/08 19:47:51 [SERVER]: finish runIITOEndOfTurn
2021/01/08 19:47:51 [SERVER]: start runIIGOTaxCommonPool
2021/01/08 19:47:51 [SERVER]: Took 0 from Team4 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team4 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team5 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team5 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team6 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team6 (reason: sanction)
2021/01/08 19:47:51 [Team1]: Paying tax: 0
2021/01/08 19:47:51 [SERVER]: Took 0 from Team1 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team1 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 50 from Team2 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team2 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team3 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team3 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: finish runIIGOTaxCommonPool
2021/01/08 19:47:51 [SERVER]: start probeDisaster
2021/01/08 19:47:51 [SERVER]: No disaster reported. No disaster effects.
2021/01/08 19:47:51 [SERVER]: finish probeDisaster
2021/01/08 19:47:51 [SERVER]: start incrementTurnAndSeason
2021/01/08 19:47:51 [SERVER]: finish incrementTurnAndSeason
2021/01/08 19:47:51 [SERVER]: start deductCostOfLiving
2021/01/08 19:47:51 [SERVER]: finish deductCostOfLiving
2021/01/08 19:47:51 [SERVER]: start updateIslandLivingStatus
2021/01/08 19:47:51 [SERVER]: finish updateIslandLivingStatus
2021/01/08 19:47:51 [SERVER]: finish endOfTurn
2021/01/08 19:47:51 [SERVER]: finish runTurn
2021/01/08 19:47:51 [SERVER]: start runTurn
2021/01/08 19:47:51 [SERVER]: TURN: 2, Season: 1
2021/01/08 19:47:51 [SERVER]: start startOfTurn
2021/01/08 19:47:51 [Team6]: Configuration has been updated
2021/01/08 19:47:51 [Team6]: Friendship information has been updated
2021/01/08 19:47:51 [Team6]: There are 6 islands left in this game
2021/01/08 19:47:51 [Team1]: Emotional state: Normal
2021/01/08 19:47:51 [Team1]: Resources: 70089.61162544173
2021/01/08 19:47:51 [Team3]: Our Status: {Resources:99968.57022603956 LifeStatus:Alive CriticalConsecutiveTurnsCounter:0}
2021/01/08 19:47:51 [SERVER]: finish startOfTurn
2021/01/08 19:47:51 [SERVER]: start runOrgs
2021/01/08 19:47:51 [SERVER]: start runIIGO
2021/01/08 19:47:51 [SERVER]: President Team3, Speaker Team1, Judge Team2
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_allocation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_allocation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_taxation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: tax_decision, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_taxation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [EXECUTIVE]: Tax: map[Team1:0 Team2:761.6037089261285 Team3:1652.0732152437645 Team4:765.1644065122572 Team5:767.7295523250228 Team6:0]
2021/01/08 19:47:51 [SERVER]: [EXECUTIVE]: Resource Allocation: map[Team1:-0 Team2:-0 Team3:16 Team4:-0 Team5:-0 Team6:-0]
2021/01/08 19:47:51 [SERVER]: Common pool resources insufficient for executiveBranch getRuleForSpeaker
2021/01/08 19:47:51 [SERVER]: finish runIIGO
2021/01/08 19:47:51 [SERVER]: start runIIFO
2021/01/08 19:47:51 [SERVER]: start runPredictionSession
2021/01/08 19:47:51 [Team3]: Final Prediction: [{NaN NaN NaN 9223372036854775808 NaN}]
2021/01/08 19:47:51 [Team4]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:51 [Team5]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:51 [Team6]: Final Prediction: [{60.64 60.64 35.64 1844674407370955264 34.7}]
2021/01/08 19:47:51 [Team1]: Final Prediction: [{1.747550432276657 1.747550432276657 1.0270893371757925 1 86.75}]
2021/01/08 19:47:51 [SERVER]: finish runPredictionSession
2021/01/08 19:47:51 [SERVER]: Run Forage Predictions
2021/01/08 19:47:51 [SERVER]: Getting Forage Information
2021/01/08 19:47:51 [Team1]: Sharing forage info: {{DeerForageType 30000} 108.89673846151409 [Team5 Team6 Team1 Team2 Team3 Team4] Team1}
2021/01/08 19:47:51 [SERVER]: Distributing Forage Information
2021/01/08 19:47:51 [SERVER]: Finish Running Forage Predictions
2021/01/08 19:47:51 [SERVER]: finish runIIFO
2021/01/08 19:47:51 [SERVER]: start runIITO
2021/01/08 19:47:51 [SERVER]: start runGiftSession
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team2]: map[Team1:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team2:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team3:{map[Foraging:[50] Gifts:[50] 
Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team4:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team5:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]} Team6:{map[Foraging:[50] Gifts:[50] Judge:[50] President:[50] Speaker:[50]] map[Gifts:{50 0}]}]
2021/01/08 19:47:51 [Team6]: The island[Team3] accepts the amount[12.909944487358057] because they [0]
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team3 from Team1: 12.909944487358057
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team6 from Team1: 10
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team2 from Team3: 12.5
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team4 from Team3: 12.5
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team5 from Team3: 12.5
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team6 from Team3: 7.341934219511391
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team1 from Team3: 15
2021/01/08 19:47:51 [SERVER]: [IITO]: Gifts to Team3 from Team6: 12.909944487358057
2021/01/08 19:47:51 [SERVER]: finish runGiftSession
2021/01/08 19:47:51 [SERVER]: start runIntendedContributionSession
2021/01/08 19:47:51 [SERVER]: finish runIntendedContributionSession
2021/01/08 19:47:51 [SERVER]: finish runIITO
2021/01/08 19:47:51 [SERVER]: finish runOrgs
2021/01/08 19:47:51 [SERVER]: start endOfTurn
2021/01/08 19:47:51 [SERVER]: start runIIGOAllocations
2021/01/08 19:47:51 [SERVER]: Gave 0 to Team3 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: Gave 0 to Team4 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: Gave 0 to Team5 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: Gave 0 to Team6 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: Gave -0 to Team1 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: Gave 0 to Team2 (reason: allocation)
2021/01/08 19:47:51 [SERVER]: finish runIIGOAllocations
2021/01/08 19:47:51 [SERVER]: start runForage
2021/01/08 19:47:51 [Team1]: [Forage decision]: flip
2021/01/08 19:47:51 [SERVER]: Took 13.934383314932695 from Team5 (reason: fishing participation)
2021/01/08 19:47:51 [SERVER]: Took 16013.162542524247 from Team6 (reason: fishing participation)
2021/01/08 19:47:51 [SERVER]: Took 27.224184615378523 from Team1 (reason: deer hunt participation)
2021/01/08 19:47:51 [SERVER]: Took 20 from Team2 (reason: fishing participation)
2021/01/08 19:47:51 [SERVER]: Took 22045.676519686545 from Team3 (reason: deer hunt participation)
2021/01/08 19:47:51 [SERVER]: Took 4.131653238273972 from Team4 (reason: fishing participation)
2021/01/08 19:47:51 [SERVER]: start runDeerHunt
2021/01/08 19:47:51 [SERVER]: Gave 0.17703569838272026 to Team1 (reason: Deer hunt return)
2021/01/08 19:47:51 [Team1]: [Forage result]: DeerForageType(27.224) | Expectation: +0.000 | Reward: +0.177 | Error: -100%
2021/01/08 19:47:51 [SERVER]: Gave 143.36046401836305 to Team3 (reason: Deer hunt return)
2021/01/08 19:47:51 [SERVER]: Deer hunt report: {"ForageType":"DeerForageType","InputResources":22072.900704301923,"NumberParticipants":2,"NumberCaught":4,"TotalUtility":143.53749971674574,"CatchSizes":[21.561438026197585,46.193530241776614,46.7142859788372,29.068245469934347],"Turn":2}
2021/01/08 19:47:51 [SERVER]: Updating deer population after 4 deer hunted
2021/01/08 19:47:51 [SERVER]: [DEERPOPULATION]: P(t): 6.04.     Population after 4 deer hunted: 4,      population at end of turn (after regeneration): 6
2021/01/08 19:47:51 [SERVER]: finish runDeerHunt
2021/01/08 19:47:51 [SERVER]: start runFishHunt
2021/01/08 19:47:51 [SERVER]: Gave 15.269618415447077 to Team5 (reason: Fishing return)
2021/01/08 19:47:51 [SERVER]: Gave 15.269618415447077 to Team6 (reason: Fishing return)
2021/01/08 19:47:51 [Team6]: Forage History Updated: Type FishForageType ,Conribution: 16013.162542524247 ,Return: 15.269618415447077
2021/01/08 19:47:51 [SERVER]: Gave 15.269618415447077 to Team2 (reason: Fishing return)
2021/01/08 19:47:51 [SERVER]: Gave 15.269618415447077 to Team4 (reason: Fishing return)
2021/01/08 19:47:51 [SERVER]: Fishing expedition report: {"ForageType":"FishForageType","InputResources":16051.228579077453,"NumberParticipants":4,"NumberCaught":6,"TotalUtility":61.07847366178831,"CatchSizes":[7.00727519786679,13.207738388473318,9.40651770152749,7.650238416718345,13.41783481401039,10.388869143191972],"Turn":2}
2021/01/08 19:47:51 [SERVER]: finish runFishHunt
2021/01/08 19:47:51 [SERVER]: finish runForage
2021/01/08 19:47:51 [SERVER]: start runIIFOEndOfTurn
2021/01/08 19:47:51 [SERVER]: finish runIIFOEndOfTurn
2021/01/08 19:47:51 [SERVER]: start runIITOEndOfTurn
2021/01/08 19:47:51 [SERVER]: Took 12.909944487358057 from Team6 (reason: TAKE: [IITO]: Team3 received gift from Team6: 12.909944487358057)
2021/01/08 19:47:51 [SERVER]: Gave 12.909944487358057 to Team3 (reason: GIVE: [IITO]: Team3 received gift from Team6: 12.909944487358057)
2021/01/08 19:47:51 [Team6]: The gift[12.909944487358057] has been sent to the island[Team3]
2021/01/08 19:47:51 [SERVER]: Took 10 from Team1 (reason: TAKE: [IITO]: Team6 received gift from Team1: 10)
2021/01/08 19:47:51 [SERVER]: Gave 10 to Team6 (reason: GIVE: [IITO]: Team6 received gift from Team1: 10)
2021/01/08 19:47:51 [Team6]: The gift[10] has been received from the island[Team1]
2021/01/08 19:47:51 [SERVER]: Took 12.909944487358057 from Team1 (reason: TAKE: [IITO]: Team3 received gift from Team1: 12.909944487358057)
2021/01/08 19:47:51 [SERVER]: Gave 12.909944487358057 to Team3 (reason: GIVE: [IITO]: Team3 received gift from Team1: 12.909944487358057)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team4 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team4 (reason: GIVE: [IITO]: Team4 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team5 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team5 (reason: GIVE: [IITO]: Team5 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Took 7.341934219511391 from Team3 (reason: TAKE: [IITO]: Team6 received gift from Team3: 7.341934219511391)
2021/01/08 19:47:51 [SERVER]: Gave 7.341934219511391 to Team6 (reason: GIVE: [IITO]: Team6 received gift from Team3: 7.341934219511391)
2021/01/08 19:47:51 [Team6]: The gift[7.341934219511391] has been received from the island[Team3]
2021/01/08 19:47:51 [SERVER]: Took 15 from Team3 (reason: TAKE: [IITO]: Team1 received gift from Team3: 15)
2021/01/08 19:47:51 [SERVER]: Gave 15 to Team1 (reason: GIVE: [IITO]: Team1 received gift from Team3: 15)
2021/01/08 19:47:51 [SERVER]: Took 12.5 from Team3 (reason: TAKE: [IITO]: Team2 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: Gave 12.5 to Team2 (reason: GIVE: [IITO]: Team2 received gift from Team3: 12.5)
2021/01/08 19:47:51 [SERVER]: finish runIITOEndOfTurn
2021/01/08 19:47:51 [SERVER]: start runIIGOTaxCommonPool
2021/01/08 19:47:51 [SERVER]: Took 767.7295523250228 from Team5 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team5 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team6 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team6 (reason: sanction)
2021/01/08 19:47:51 [Team1]: Paying tax: 0
2021/01/08 19:47:51 [SERVER]: Took 0 from Team1 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team1 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 761.6037089261285 from Team2 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 9996 from Team2 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team3 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team3 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: Took 765.1644065122572 from Team4 (reason: tax)
2021/01/08 19:47:51 [SERVER]: Took 0 from Team4 (reason: sanction)
2021/01/08 19:47:51 [SERVER]: finish runIIGOTaxCommonPool
2021/01/08 19:47:51 [SERVER]: start probeDisaster
2021/01/08 19:47:51 [SERVER]: No disaster reported. No disaster effects.
2021/01/08 19:47:51 [SERVER]: finish probeDisaster
2021/01/08 19:47:51 [SERVER]: start incrementTurnAndSeason
2021/01/08 19:47:51 [SERVER]: finish incrementTurnAndSeason
2021/01/08 19:47:51 [SERVER]: start deductCostOfLiving
2021/01/08 19:47:51 [SERVER]: finish deductCostOfLiving
2021/01/08 19:47:51 [SERVER]: start updateIslandLivingStatus
2021/01/08 19:47:51 [SERVER]: finish updateIslandLivingStatus
2021/01/08 19:47:51 [SERVER]: finish endOfTurn
2021/01/08 19:47:51 [SERVER]: finish runTurn
2021/01/08 19:47:51 [SERVER]: start runTurn
2021/01/08 19:47:51 [SERVER]: TURN: 3, Season: 1
2021/01/08 19:47:51 [SERVER]: start startOfTurn
2021/01/08 19:47:51 [Team6]: Configuration has been updated
2021/01/08 19:47:51 [Team6]: Friendship information has been updated
2021/01/08 19:47:51 [Team6]: There are 6 islands left in this game
2021/01/08 19:47:51 [Team1]: Emotional state: Normal
2021/01/08 19:47:51 [Team1]: Resources: 70044.65453203737
2021/01/08 19:47:51 [Team3]: Our Status: {Resources:78022.23212512658 LifeStatus:Alive CriticalConsecutiveTurnsCounter:0}
2021/01/08 19:47:51 [SERVER]: finish startOfTurn
2021/01/08 19:47:51 [SERVER]: start runOrgs
2021/01/08 19:47:51 [SERVER]: start runIIGO
2021/01/08 19:47:51 [SERVER]: President Team3, Speaker Team1, Judge Team2
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_sanction_rule, broken by: Team2
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_sanction_rule, broken by: Team2
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_allocation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_allocation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_taxation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: tax_decision, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_taxation_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_sanction_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [JUDICIARY]: Rule: check_sanction_rule, broken by: Team3
2021/01/08 19:47:51 [SERVER]: [EXECUTIVE]: Tax: map[Team1:0 Team2:0 Team3:0 Team4:0 Team5:0 Team6:0]
2021/01/08 19:47:51 [SERVER]: [EXECUTIVE]: Resource Allocation: map[Team1:-0 Team2:-0 Team3:70 Team4:-0 Team5:-0 Team6:-0]
2021/01/08 19:47:51 [SERVER]: [LEGISLATURE]: Rule vote with islands [Team6 Team1 Team2 Team3 Team4 Team5] allowed to vote
2021/01/08 19:47:51 [SERVER]: [RULE VOTE]: Votes: [Abstain Approve Approve Approve Approve Approve]
2021/01/08 19:47:51 [SERVER]: [LEGISLATURE]: Rule: allocation_decision , voted in by islands: true , result heeded by speaker: true
2021/01/08 19:47:51 [SERVER]: finish runIIGO
2021/01/08 19:47:51 [SERVER]: finish runOrgs
2021/01/08 19:47:51 [SERVER]: finish runTurn
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x110 pc=0x940130]

goroutine 1 [running]:
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.(*monitor).findRoleToMonitor(0xb5e720, 0x0, 0x8, 0x1, 0x1, 0x2)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/iigointernal/monitoring.go:104 +0x30
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.(*monitor).monitorRole(0xb5e720, 0xa33b20, 0xc000120000, 0xc0000493c8)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/iigointernal/monitoring.go:39 +0x6f
github.com/SOMAS2020/SOMAS2020/internal/server/iigointernal.RunIIGO(0xc0000346c0, 0xc000138000, 0xc0001382f0, 0xc000138128, 0x3, 0x40c8013fb393c80e, 0xc00006a8d0)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/iigointernal/orchestration.go:219 +0x15e5
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runIIGO(0xc000138000, 0x0, 0x0)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/iigo.go:17 +0x1f8
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runOrgs(0xc000138000, 0x0, 0x0)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/turn.go:43 +0xde
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).runTurn(0xc000138000, 0x0, 0x0)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/turn.go:18 +0x1a9
github.com/SOMAS2020/SOMAS2020/internal/server.(*SOMASServer).EntryPoint(0xc000138000, 0x64, 0x40f86a0000000000, 0x4059000000000000, 0x4024000000000000, 0x4014000000000000)
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/internal/server/server.go:135 +0x1c8
main.main()
        C:/Users/lhlee/Documents/SOMAS/SOMAS2020/main.go:64 +0x41f
exit status 2
```

### PR DESCRIPTION
**Pull request by Neelesh99**
# Summary

Small bug in Team 6 judge, array not initialised. @Diregie-J @Regnigh 

Hopefully fixes #359 

## Test Plan

Passes tests.

### CODE REVIEW

File: internal/clients/team6/judge.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ func (j *judge) GetPardonedIslands(currentSanctions map[int][]shared.Sanction) m
 
 	for timeStep, sanctions := range currentSanctions {
 		for who, sanction := range sanctions {
+			pardons[timeStep] = initialiseBoolArray(len(sanctions))
```
Comment (lhl2617) [inline internal/clients/team6/judge.go]:
```suggestion
			pardons[timeStep] = make([]bool, len(sanctions))
```

Default value for bools is `false` :)

Comment (Neelesh99) [reply internal/clients/team6/judge.go]: My god, I'd no idea

Comment (Neelesh99) [reply internal/clients/team6/judge.go]: Thanks, latest commit does this and removes function

File: internal/clients/team6/judge.go [hunk 2]
```diff
@@ -16,6 +16,7 @@ func (j *judge) GetPardonedIslands(currentSanctions map[int][]shared.Sanction) m
 
 	for timeStep, sanctions := range currentSanctions {
 		for who, sanction := range sanctions {
+			pardons[timeStep] = make([]bool, len(sanctions))
```
Comment (lhl2617) [inline internal/clients/team6/judge.go]:
```suggestion
		pardons[timeStep] = make([]bool, len(sanctions))
		for who, sanction := range sanctions {
```

Comment (lhl2617) [reply internal/clients/team6/judge.go]: shouldnt these two lines be swapped around?

Comment (Neelesh99) [reply internal/clients/team6/judge.go]: Soz, brain not working

Comment (dejay-vu) [reply internal/clients/team6/judge.go]: Ohhh just saw this sry for this stupid mistake. Thx for the correction!

**Review by Ning-72 — APPROVED** [review]
