### PR TITLE
[IIFO] Fix IIFO disaster prediction

### LINKED ISSUE #120: Check  the distributePredicition function in IIFO
Potential loop break when assigning nil to array being iterated over

### PR DESCRIPTION
**Pull request by Eirikalb**
Close #120 
# Summary
Added some testing to verify distribution of predictions happens correctly, ie messages are only sent when intended and only alive clients are allowed to send and receive predictions. Also changed some naming.
## Additional Information
The branch is based off the branch #194 so it has some clutter, might be easiest to only merge this PR and close the other one.

## Test Plan

Extended IIFO serverside testing for disaster predictions inspired by #132

### CODE REVIEW

**Comment by QFSW** [comment]
# ⚠️Warning! This diff contains changes in protected folders

File: internal/common/baseclient/iifo.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ type PastDisastersList = []DisasterInfo
 // MakePrediction is called on each client for them to make a prediction about a disaster
 // Prediction includes location, magnitude, confidence etc
 // COMPULSORY, you need to implement this method
-func (c *BaseClient) MakePrediction() (shared.PredictionInfo, error) {
+func (c *BaseClient) MakePrediction() shared.PredictionInfo {
```
Comment (E-Mac27) [inline internal/common/baseclient/iifo.go]: Nitpick: Rename this to MakeDisasterPrediction()

File: internal/common/baseclient/iifo.go [hunk 2]
```diff
@@ -113,13 +107,13 @@ func determineConfidence(pastDisastersList PastDisastersList, meanDisaster Disas
...
 	// Return the confidence of the prediction
-	return math.Round(varianceLimit - averageVariance), nil
+	return math.Round(varianceLimit - averageVariance)
 }
 
 // ReceivePredictions provides each client with the prediction info, in addition to the source island,
 // that they have been granted access to see
 // COMPULSORY, you need to implement this method
-func (c *BaseClient) ReceivePredictions(receivedPredictions shared.PredictionInfoDict) error {
+func (c *BaseClient) ReceivePredictions(receivedPredictions shared.ReceivedDisasterPredictionsDict) {
```
Comment (E-Mac27) [inline internal/common/baseclient/iifo.go]: Nitpick: Rename ReceiveDisasterPredictions()

File: internal/server/iifo_test.go [hunk 3]
```diff
@@ -50,6 +60,26 @@ func receiveForagingInfo(contribution shared.Resources, resources shared.Resourc
...
 }
 
+func makeDisasterPrediction(prediction shared.Prediction, shareTo []shared.ClientID) shared.PredictionInfo {
+	if len(shareTo) > 0 {
+		return shared.PredictionInfo{
+			PredictionMade: prediction,
+			TeamsOfferedTo: shareTo,
+		}
+	}
+	// People can be selfish and choose not to share their foraging information
```
Comment (E-Mac27) [inline internal/server/iifo_test.go:69]: change foraging -> disaster prediction

File: internal/server/iifo.go [hunk 4]
```diff
@@ -53,49 +41,41 @@ func (s *SOMASServer) runForageSharing() {
...
+	reorderDictionary := make(map[shared.ClientID]shared.ReceivedDisasterPredictionsDict)
 	// Add the predictions/sources to the dict containing which predictions each island should receive
 	// Don't allow teams to know who else these predictions were shared with in MVP
+	nonDeadClients := getNonDeadClientIDs(s.gameState.ClientInfos)
+
 	for idSource, info := range islandPredictionDict {
-		for _, idShare := range info.TeamsOfferedTo {
-			if idShare == idSource {
-				continue
+		if clientArrayContains(nonDeadClients, idSource) {
```
Comment (NGovani) [inline internal/server/iifo.go:61]: you only get predictions from non dead clients, does this check need to be done?

File: internal/server/iifo.go [hunk 5]
```diff
@@ -53,49 +41,41 @@ func (s *SOMASServer) runForageSharing() {
...
+			for _, idShare := range info.TeamsOfferedTo {
+				if idShare == idSource {
+					continue
+				}
+				if reorderDictionary[idShare] == nil {
+					reorderDictionary[idShare] = make(shared.ReceivedDisasterPredictionsDict)
+				}
+				reorderDictionary[idShare][idSource] = shared.ReceivedDisasterPredictionInfo{PredictionMade: info.PredictionMade, SharedFrom: idSource}
```
Comment (E-Mac27) [inline internal/server/iifo.go:69]: SharedFrom variable is redundant. 

reorderDictionary already holds the SharedFrom aspect.

File: internal/server/iifo_test.go [hunk 6]
```diff
@@ -146,3 +176,63 @@ func TestDistributeForageSharing(t *testing.T) {
...
+		Confidence:  100,
+	}
+	input := shared.PredictionInfoDict{
+		shared.Team1: makeDisasterPrediction(team1Prediction, []shared.ClientID{shared.Team2, shared.Team3}),
+		shared.Team2: makeDisasterPrediction(shared.Prediction{}, []shared.ClientID{}),
+		shared.Team3: makeDisasterPrediction(shared.Prediction{}, []shared.ClientID{shared.Team1, shared.Team2}),
+	}
+	want := map[shared.ClientID]shared.ReceivedDisasterPredictionsDict{
+		shared.Team1: shared.ReceivedDisasterPredictionsDict(nil),
+		shared.Team2: {shared.Team1: receiveDisasterPrediction(team1Prediction, shared.Team1)},
```
Comment (E-Mac27) [inline internal/server/iifo_test.go:217]: This is a follow on from a previous comment since this is more easily noticeable here: The SharedFrom variable isn't needed.

File: internal/server/iifo_test.go [hunk 7]
```diff
@@ -11,8 +11,10 @@ import (
 
 type mockClientIIFO struct {
 	baseclient.Client
-	foragingValues  shared.ForageShareInfo
-	otherIslandInfo []shared.ForageShareInfo
+	foragingValues                shared.ForageShareInfo
+	otherIslandInfo               []shared.ForageShareInfo
+	ownPrediction                 shared.PredictionInfo
```
Comment (NGovani) [inline internal/server/iifo_test.go]: linter issue ownPrediction is unused apparently

**Review by E-Mac27 — COMMENTED** [review]
Overall great PR! Nothing breaks the game per say. I mainly left nitpicks and one potential change.

**Review by NGovani — CHANGES_REQUESTED** [review]
changes look good, nothing major needs to be fixed

File: internal/server/iifo.go (hunk 4 above)
Comment (Eirikalb) [reply internal/server/iifo.go:61]: Not really, but figured it didnt hurt to have it in there

File: internal/server/iifo_test.go (hunk 7 above)
Comment (Eirikalb) [reply internal/server/iifo_test.go]: True didnt need it in the end.

File: internal/server/iifo.go (hunk 5 above)
Comment (Eirikalb) [reply internal/server/iifo.go:69]: Yeah thats true... Doesnt hurt to have it in twice though

File: internal/server/iifo_test.go (hunk 6 above)
Comment (Eirikalb) [reply internal/server/iifo_test.go:217]: Yeah I see what you mean now, is this why you went for the array instead?

Comment (E-Mac27) [reply internal/server/iifo_test.go:217]: Its more like I didn't think about making it into a map. IMO both works. It's just if you are using maps, then you don't need that ShareFrom variable. But I agree that it doesn't harm the game if both are added.

Comment (E-Mac27) [reply internal/server/iifo_test.go:217]: Maps > Array lol. oh well past me.

**Review by NGovani — APPROVED** [review]
Yup looks good ill merge
